### PR TITLE
Add a Project.TOML file

### PR DESCRIPTION
**Pull request by simonschoelly**
- Bump version to 0.3.0
- Remove REQUIRE files
- Remove Julia v0.7 from testing pipeline
- Add Julia v1.5 to testing pipeline

### CODE REVIEW

**Comment by greimel** [comment]
You can use julia 1 as the current 1.x release. (Check the CI files in CategoricalArrays.jl). So, use julia 1.0 and julia 1

(from my phone)

**Comment by SimonDanisch** [comment]
I'll fork this PR and also switch to GeometryBasics & fix tests!

**Comment by SimonDanisch** [comment]
Thanks!

**Comment by simonschoelly** [comment]
> You can use julia 1 as the current 1.x release. (Check the CI files in CategoricalArrays.jl). So, use julia 1.0 and julia 1
> 
> (from my phone)

Thanks, didn't know that.

@SimonDanisch Would be good if afterwards you could also ping the release bot and add a new tag.

**Comment by SimonDanisch** [comment]
https://github.com/JuliaRegistries/General/pull/23159

**Pull request merged**
