### PR TITLE
Remove * method for StridedVector of StaticArray

### PR DESCRIPTION
**Pull request by tkelman**
tests don't seem to need this to pass, re: https://github.com/JuliaGraphs/NetworkLayout.jl/commit/72ef209ced3597fa0e771ce46c678dc325dbb75e#commitcomment-23382073

### CODE REVIEW

**Comment by tkelman** [comment]
@SimonDanisch can you recall what you added this for in https://github.com/JuliaGraphs/NetworkLayout.jl/pull/5/files?w=1#diff-610f019f278cdca175571470b13b16c6R56 ?

**Comment by SimonDanisch** [comment]
I don't, but I'm pretty sure that it was a work around for a bug and not actually relevant...

**Comment by sbromberger** [comment]
Thanks, @tkelman and @SimonDanisch !

**Comment by tkelman** [comment]
Thanks. Could you amend the tag for this? See the attobot readme

**Pull request merged**
