### PR TITLE
buchheim fix; closes #7

### LINKED ISSUE #7: Error in Buchheim
```julia
julia> using NetworkLayout

julia> adjlist = Array{Int64,1}[[2,10],[3,4,5,6,9],Int64[],Int64[],Int64[],[7,8],Int64[],Int64[],Int64[],[11,19,27,44],[12,13],Int64[],[14,15,18],Int64[],[16,17],Int64[],Int64[],Int64[],[20,21,22],Int64[],Int64[],[23,24],Int64[],[25,26],Int64[],Int64[],[28,29,30],Int64[],Int64[],[31,32],Int64[],[33,39],[34,35,36,37,38],Int64[],Int64[],Int64[],Int64[],Int64[],[40,41],Int64[],[42,43],Int64[],Int64[],Int64[]];

julia> NetworkLayout.Buchheim.layout(adjlist)
ERROR: ArgumentError: invalid index: 23.0
 in getindex(::Array{Float64,1}, ::Float64) at ./array.jl:386
 in apportion(::Int64, ::Int64, ::NetworkLayout.Buchheim.Tree{Array{Array{Int64,1},1},Array{FixedSizeArrays.Point{2,Float64},1},Array{Float64,1}}) at /home/tom/.julia/v0.5/NetworkLayout/src/buchheim.jl:128
 in first_walk(::Int64, ::NetworkLayout.Buchheim.Tree{Array{Array{Int64,1},1},Array{FixedSizeArrays.Point{2,Float64},1},Array{Float64,1}}) at /home/tom/.julia/v0.5/NetworkLayout/src/buchheim.jl:86
 in first_walk(::Int64, ::NetworkLayout.Buchheim.Tree{Array{Array{Int64,1},1},Array{FixedSizeArrays.Point{2,Float64},1},Array{Float64,1}}) at /home/tom/.julia/v0.5/NetworkLayout/src/buchheim.jl:85
 in layout! at /home/tom/.julia/v0.5/NetworkLayout/src/buchheim.jl:49 [inlined]
 in #layout#3 at /home/tom/.julia/v0.5/NetworkLayout/src/buchheim.jl:44 [inlined]
 in layout(::Array{Array{Int64,1},1}) at /home/tom/.julia/v0.5/NetworkLayout/src/buchheim.jl:44
```

### PR DESCRIPTION
**Pull request by tbreloff**
fixes https://github.com/JuliaGraphs/NetworkLayout.jl/issues/7 (though I admit I didn't stop to think whether this is the best fix... just that it works)

### CODE REVIEW

**Comment by SimonDanisch** [comment]
I think it's not the right way ;) threads should be an Integer array to begin with, from all I can tell...

**Comment by abhijithanilkumar** [comment]
The tests are failing since LightGraphs has changed the package requirements :sweat_smile: . Should we remove 0.4 support as well?

**Comment by SimonDanisch** [comment]
Might as well ;)

**Comment by abhijithanilkumar** [comment]
travis.yml also needs to be modified to stop running tests on 0.4

**Comment by tbreloff** [comment]
Great thanks!

**Pull request merged**
