### PR TITLE
Update dependencies, Julia compat, and add weak dependencies

### PR DESCRIPTION
**Pull request by devmotion**
This PR updates the list of dependencies: SparseArrays is not needed anymore, it seems https://github.com/JuliaGraphs/NetworkLayout.jl/pull/40 removed the use of SparseMatrixCSC in src/stress.jl This cleanup is very helpful since in Julia >= 1.10 will not be included anymore in the default system image and therefore there is an effort throughout the ecosystem to make SparseArrays a weak dependency whenever possible. Removing it from NetworkLayout means that it won't trigger the compilation and loading of these extensions.

I used the opportunity and additionally moved the support for LightGraphs and Graphs in Julia >= 1.9 to extensions. Moreover, when testing the PR I noticed that the package, or rather its dependencies, are not compatible with Julia 1.0 anymore (even though according to the Project.toml file Julia >= 1.0 is supported). Since the CI runs only with Julia >= 1.6 I bumped the Julia compat entry to 1.6.

### CODE REVIEW

**Comment by simonschoelly** [comment]
This package is not really maintained much by the people that maintain Graphs.jl - I think its mostly used by GraphMakie.jl, so I cannot comment much here - but maybe two questions:
1. Is there a good reason to keep the support for LightGraphs.jl? The only dependencies of this package that still have LightGraphs as a dependency are [PlasmoPlots.jl](https://github.com/plasmo-dev/PlasmoPlots.jl) and [Nodariety.jl](https://github.com/rkurchin/Nodariety.jl) - and I am not sure if these are even still developed.

2. Are weak dependencies already supported by Julia 1.6?

**Comment by devmotion** [comment]
> 1. Is there a good reason to keep the support for LightGraphs.jl?

I was wondering the same but since I'm not a regular contributor to this package I thought it would be best to not perform any major changes, in particular since it did not cause any dependency incompatibilities.

> 2. Are weak dependencies already supported by Julia 1.6?

No, weak dependencies are only supported by Julia >= 1.9. On Julia < 1.9, the PR does not change the current behaviour and the additional support for Graphs and LightGraphs will be loaded optionally with Requires.

**Comment by hexaeder** [comment]
I think it is totally fine to drop LightGraphs support, it was only important during the transition. I also changed the doc build for Documenter@1.0.

Thanks for the PR anyway! The move to PkgExtension was overdue.

**Comment by cormullion** [comment]
> its mostly used by GraphMakie.jl

plus BioLab.jl, EvoTrees.jl, GraphRecipes.jl, ITensorMakie.jl, ITensorUnicodePlots.jl, ITensorVisualizationBase.jl, Karnak.jl, MINDFulMakie.jl, NestedGraphMakie.jl, Nodariety.jl, OptimizedEinsum.jl, PlantGraphs.jl, PlasmoPlots.jl, PowerPlots.jl, PowerSystemsMaps.jl, QUBOTools.jl, QuantumSavory.jl, TreeRecipe.jl ... :)

**Comment by simonschoelly** [comment]
> > its mostly used by GraphMakie.jl
> 
> plus BioLab.jl, EvoTrees.jl, GraphRecipes.jl, ITensorMakie.jl, ITensorUnicodePlots.jl, ITensorVisualizationBase.jl, Karnak.jl, MINDFulMakie.jl, NestedGraphMakie.jl, Nodariety.jl, OptimizedEinsum.jl, PlantGraphs.jl, PlasmoPlots.jl, PowerPlots.jl, PowerSystemsMaps.jl, QUBOTools.jl, QuantumSavory.jl, TreeRecipe.jl ... :)

You are right, I should have mentioned that. I did check the packages that have `NetworkLayout.jl` as a dependency though (not recusively, maybe I should have) and apart from the two that I have mentioned, they don't use LightGraphs.jl

**Pull request merged**
